# Generated by Django 6.1.1 on 2026-09-21 09:04

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="S3Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("endpoint", models.CharField(max_length=500)),
                ("access_key", apps.core.fields.EncryptedCharField(max_length=500)),
                ("secret_key", apps.core.fields.EncryptedCharField(max_length=500)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("use_ssl", models.BooleanField(default=True)),
                ("path_style", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="s3_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
