# Generated by Django 6.1.1 on 2026-09-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0002_s3connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnglitejob",
            name="layers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
