# Generated by Django 6.1.1 on 2026-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0003_cnglitejob_layers"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnglitejob",
            name="output_keys",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
