# Generated by Django 6.1.1 on 2026-09-21 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0004_cnglitejob_output_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayerCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("owner_id", models.CharField(max_length=255)),
                ("connection_id", models.CharField(max_length=255)),
                ("bucket", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("source_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LayerCollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.TextField()),
                ("format", models.CharField(max_length=10)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cloudbench_s3.layercollection",
                    ),
                ),
            ],
        ),
    ]
