# Generated by Django 6.1.1 on 2026-09-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0005_layercollection_layercollectionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3connection",
            name="bucket",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
