# Generated by Django 6.1.1 on 2026-09-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0007_split_connections_per_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnglitejob",
            name="license",
            field=models.CharField(blank=True, default="other", max_length=100),
        ),
    ]
