# Generated by Django 6.1.1 on 2026-09-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0008_cnglitejob_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3connection",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
