# Generated by Django 6.1.1 on 2026-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloudbench_s3", "0009_s3connection_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnglitejob",
            name="license_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
    ]
