# Generated by Django 6.1.1 on 2026-09-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloudbench_s3", "0010_cnglitejob_license_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnglitejob",
            name="replace_existing",
            field=models.BooleanField(default=False),
        ),
    ]
