# Generated by Django 6.1.1 on 2026-09-28 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cloudbench_s3", "0011_cnglitejob_replace_existing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layercollectionitem",
            name="collection",
        ),
        migrations.DeleteModel(
            name="LayerCollection",
        ),
        migrations.DeleteModel(
            name="LayerCollectionItem",
        ),
    ]
