# Generated by Django 6.1.1 on 2026-10-01 05:48

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0012_drop_layer_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnglitejob",
            name="cloudnativegis_api_token",
            field=apps.core.fields.EncryptedCharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="cnglitejob",
            name="cloudnativegis_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
    ]
