# Generated by Django 6.1.1 on 2026-10-01 07:13

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0012_drop_layer_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnglitejob",
            name="cloudnativegis_api_token",
            field=apps.core.fields.EncryptedCharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="cnglitejob",
            name="cloudnativegis_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="cnglitejob",
            name="cng_job_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="cnglitejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("provisioning", "Provisioning"),
                    ("pushing", "Pushing"),
                    ("polling", "Polling"),
                    ("downloading", "Downloading"),
                    ("publishing", "Publishing"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
