# Generated by Django 6.1.1 on 2026-10-02 05:42

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0014_cnglitejob_owner_connection_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnglitejob",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("provisioning", "Provisioning"),
                    ("pushing", "Pushing"),
                    ("polling", "Polling"),
                    ("downloading", "Downloading"),
                    ("publishing", "Publishing"),
                    ("running", "Running"),
                    ("deprovisioning", "Deprovisioning"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cnglitejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("provisioning", "Provisioning"),
                    ("pushing", "Pushing"),
                    ("polling", "Polling"),
                    ("downloading", "Downloading"),
                    ("publishing", "Publishing"),
                    ("running", "Running"),
                    ("deprovisioning", "Deprovisioning"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CngLiteJobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("step", models.CharField(max_length=20)),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("geohosting", "GeoHosting"),
                            ("cloudnativegis", "CloudNativeGIS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("url", models.CharField(max_length=2000)),
                (
                    "request_payload",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "response_payload",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="cloudbench_s3.cnglitejob",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
    ]
