# Generated by Django 6.1.1 on 2026-10-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0016_cnglitejob_outcome_alter_cnglitejob_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnglitejob",
            name="hetzner_server_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cnglitejob",
            name="hetzner_server_specification",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
