# Generated by Django 6.1.1 on 2026-10-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudbench_s3", "0017_cnglitejob_hetzner_server_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnglitejob",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("provisioning", "Provisioning"),
                    ("pushing", "Pushing"),
                    ("polling", "Polling"),
                    ("verifying", "Verifying"),
                    ("publishing", "Publishing"),
                    ("deprovisioning", "Deprovisioning"),
                    ("cancelling", "Cancelling"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cnglitejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("provisioning", "Provisioning"),
                    ("pushing", "Pushing"),
                    ("polling", "Polling"),
                    ("verifying", "Verifying"),
                    ("publishing", "Publishing"),
                    ("deprovisioning", "Deprovisioning"),
                    ("cancelling", "Cancelling"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
