# Generated by Django 6.1.1 on 2026-09-30 03:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoNodeConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("connection_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=500)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                (
                    "password",
                    apps.core.fields.EncryptedCharField(blank=True, default="", max_length=500),
                ),
                (
                    "api_key",
                    apps.core.fields.EncryptedCharField(blank=True, default="", max_length=4000),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoNode connection",
                "ordering": ["created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "connection_id"),
                        name="cloudbench_geonode_geonodeconnection_unique_owner_connection_id",
                    )
                ],
            },
        ),
    ]
